# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-19 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseRefName', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('state', models.CharField(default='', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('title', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('merged_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('state', models.CharField(default='', max_length=20)),
                ('title', models.CharField(default='', max_length=250)),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GithubAPIGraphs.Branche')),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('user', models.CharField(default='', max_length=150)),
                ('repository', models.CharField(default='', max_length=150, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='pr',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GithubAPIGraphs.Website'),
        ),
        migrations.AddField(
            model_name='issue',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GithubAPIGraphs.Website'),
        ),
        migrations.AddField(
            model_name='branche',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GithubAPIGraphs.Website'),
        ),
    ]
