# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-26 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GithubAPIGraphs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='cursor',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pr',
            name='cursor',
            field=models.CharField(default='', max_length=50),
        ),
    ]
