# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GithubAPIGraphs', '0002_auto_20170726_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='website',
        ),
        migrations.AddField(
            model_name='website',
            name='token',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
