# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GithubAPIGraphs', '0003_auto_20170810_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='token',
        ),
    ]
