# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GithubAPIGraphs', '0004_remove_website_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_websites',
            fields=[
                ('user', models.CharField(default='', max_length=150)),
                ('repository', models.CharField(default='', max_length=150, primary_key=True, serialize=False)),
            ],
        ),
    ]
