# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-11 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GithubAPIGraphs', '0005_add_websites'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add_websites',
            new_name='Add_website',
        ),
    ]
